### ISSUE TITLE
Users without full access cannot view globe objects

### ISSUE THREAD

**Issue by Copis** [Mikesch-mp/icingaweb2-module-globe#1]
Hi,

Maybe i'm doing something wrong but i try to create a user for a zone with limited privileges and even with full access the globe module is not showing any object.

The problem appears when i apply a filter to monitoring elements
monitoring/filter/objects -> hostgroup_name=groupX.

I don't know how this module works, there are some log file to review?

Of course this could be an error of icingaweb2. In that case i will open an issue in yours git

**Comment by Mikesch-mp** [comment]
Hello,

 

i will try to check this this weekend.

 

Best regards,

 

Carsten

 

Gesendet: Donnerstag, 01. Dezember 2016 um 12:19 Uhr
Von: Copis <notifications@github.com>
An: Mikesch-mp/icingaweb2-module-globe <icingaweb2-module-globe@noreply.github.com>
Betreff: [Mikesch-mp/icingaweb2-module-globe] Users without full access cannot view globe objects (#1)


Hi,

Maybe i'm doing something wrong but i try to create a user for a zone with limited privileges and even with full access the globe module is not showing any object.

The problem appears when i apply a filter to monitoring elements
monitoring/filter/objects -> hostgroup_name=groupX.

I don't know how this module works, there are some log file to review?

Of course this could be an error of icingaweb2. In that case i will open an issue in yours git

**Comment by Mikesch-mp** [comment]
Found and fixed the bug :)

**Comment by Copis** [comment]
Now works fine

Thanks!
